version: "3.9"
services:
  wireguard:
    container_name: wireguard
    build:
      context: .
      dockerfile: ./wireguard.Dockerfile
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - TZ=America/Los_Angeles
      - LOCAL_SUBNETS=10.0.0.0/24
    volumes:
      - /lib/modules:/lib/modules
      - ./wireguard/configs:/etc/wireguard
    dns:
      - 10.64.0.1
    sysctls:
      net.ipv4.ip_forward: 1
      net.ipv4.conf.all.src_valid_mark: 1
      net.ipv6.conf.all.disable_ipv6: 1
    privileged: true
    restart: unless-stopped

  transmission:
    container_name: transmission
    build:
      context: .
      dockerfile: ./transmission.Dockerfile
    network_mode: service:wireguard
    depends_on:
      - wireguard
    environment:
      - TZ=America/Los_Angeles
    volumes:
      - ./transmission:/root/.config/transmission-daemon:rw
      - /var/lib/transmission-daemon/downloads:/var/lib/transmission-daemon/downloads:rw
    sysctls:
      net.ipv6.conf.all.disable_ipv6: 1
    restart: unless-stopped

  nginx:
    build:
      context: .
      dockerfile: ./nginx.Dockerfile
    image: nginx
    container_name: nginx
    volumes:
      - ./ssl:/etc/ssl
    ports:
      - "42069:42069"
    links:
      - wireguard:transmission
    depends_on:
      - transmission
    sysctls:
      net.ipv6.conf.all.disable_ipv6: 1
    restart: unless-stopped
