version: "3.9"
services:
  wireguard:
    image: linuxserver/wireguard:latest
    container_name: wireguard
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
    volumes:
      - ./wireguard/wgo.conf:/config/wg0.conf
    sysctls:
      net.ipv4.conf.all.src_valid_mark: 1
    ports:
      - 9091:9091
    restart: unless-stopped

  transmission:
    image: linuxserver/transmission:latest
    container_name: transmission
    network_mode: service:airvpn
    depends_on:
      - wireguard
    volumes:
      - ./transmission/config:/config:rw
      - /downloads:/downloads:rw
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
    env_file:
      - ./.env
    restart: unless-stopped

  nginx:
    container_name: nginx
    image: nginx:latest
    volumes:
      - ./nginx/log:/var/log/nginx
      - ./nginx/keys:/config/keys
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    env_file:
      - ./.env
    ports:
      - ${RPCPORT}:80
    depends_on:
      - transmission
    restart: unless-stopped
